In [140]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [141]:
df_factors = pd.read_excel('factor_pricing_data_monthly.xlsx', sheet_name='factors (excess returns)')
df_factors.set_index('Date', inplace=True)
df_test = pd.read_excel('factor_pricing_data_monthly.xlsx', sheet_name='portfolios (excess returns)')
df_test.set_index('Date', inplace=True)

In [142]:
AnnualizationFactor = 12

In [143]:
df_factors.head()

MKT     SMB     HML     RMW     CMA     UMD
Date                                                      
1980-01-31  0.0550  0.0188  0.0185 -0.0184  0.0189  0.0745
1980-02-29 -0.0123 -0.0162  0.0059 -0.0095  0.0292  0.0789
1980-03-31 -0.1289 -0.0697 -0.0096  0.0182 -0.0105 -0.0958
1980-04-30  0.0396  0.0105  0.0103 -0.0218  0.0034 -0.0048
1980-05-31  0.0526  0.0200  0.0038  0.0043 -0.0063 -0.0118

### Question 1

In [144]:
reg_dict = {}
alpha_AQR = []
model = LinearRegression()
X = df_factors[['MKT', 'HML', 'RMW', 'UMD']]
for col in df_test.columns:
    y = df_test[col]
    model.fit(X, y)
    alpha = model.intercept_.item() * AnnualizationFactor
    reg_dict[col] = (alpha, model.score(X,y))
    alpha_AQR.append(abs(alpha))
reg_dict

{'Agric': (0.011650699285749376, 0.3420744836499603),
 'Food ': (0.0015000694207832482, 0.4550642791648296),
 'Soda ': (0.015381493846173152, 0.3025437337801121),
 'Beer ': (0.009853401314914738, 0.414773181901106),
 'Smoke': (0.04110970733257899, 0.26536292831592934),
 'Toys ': (-0.033703810105509324, 0.510212934872883),
 'Fun  ': (0.03906454959762441, 0.6072125378429298),
 'Books': (-0.03670532389830129, 0.6889331824147402),
 'Hshld': (-0.012743345582406546, 0.5547117301752084),
 'Clths': (-0.022670009931975127, 0.6189681968042005),
 'Hlth ': (-0.04067722687103768, 0.44085804954081087),
 'MedEq': (0.016367917280677668, 0.5957805838064066),
 'Drugs': (0.02564695075029726, 0.4893819171211329),
 'Chems': (-0.035134538873798325, 0.7452255326428552),
 'Rubbr': (-0.004521308502526602, 0.6453147340172991),
 'Txtls': (-0.03674377137199987, 0.5470222398043796),
 'BldMt': (-0.02863197396848767, 0.752532273230015),
 'Cnstr': (-0.03531633690925022, 0.631499987539843),
 'Steel': (-0.0324237140792

In [145]:
model.coef_

array([ 1.0456675 ,  0.09872946,  0.13453947, -0.02178884])

### Question 2.

In [146]:
MAE_AQR = sum(alpha_AQR) / len(alpha_AQR)
MAE_AQR

0.024610849041637902

#### Answer 2

The MAE is not that small: .024. This would indicate that around 2.4% of the returns cannot be explained by AQR's factors.

### Question 2(2).

In [147]:
### CAPM
reg_dict = {}
alpha_CAPM = []
model = LinearRegression()
X = df_factors[['MKT']]
for col in df_test.columns:
    y = df_test[col]
    model.fit(X, y)
    alpha = model.intercept_.item() * AnnualizationFactor
    reg_dict[col] = (alpha, model.score(X,y))
    alpha_CAPM.append(abs(alpha))
reg_dict

{'Agric': (0.02371623986704579, 0.3332502451738336),
 'Food ': (0.03958754949806073, 0.3540606007098035),
 'Soda ': (0.04520498460287084, 0.2449244211819548),
 'Beer ': (0.05150934672462387, 0.32440885544918807),
 'Smoke': (0.0859621301071104, 0.18214080949290135),
 'Toys ': (-0.03519885363561513, 0.4962543693002631),
 'Fun  ': (0.011039167344629605, 0.5860708187673752),
 'Books': (-0.023611750637821182, 0.6551385634452895),
 'Hshld': (0.01651932293641418, 0.4862175096743381),
 'Clths': (-0.004743733621000883, 0.5607423298383393),
 'Hlth ': (-0.003261345630737128, 0.4057529778322091),
 'MedEq': (0.020229640470551195, 0.5855047992768456),
 'Drugs': (0.03652299398935285, 0.46662457302723925),
 'Chems': (-0.014269894705647355, 0.6845456969441337),
 'Rubbr': (0.0014125516265436344, 0.634287624497914),
 'Txtls': (-0.02425969429568863, 0.43106338969014824),
 'BldMt': (-0.002437408232968362, 0.6949234926859056),
 'Cnstr': (-0.012272319094955311, 0.6106908475983202),
 'Steel': (-0.057539297257

In [148]:
model.coef_

array([1.01728733])

In [149]:
MAE_CAPM = sum(alpha_CAPM) / len(alpha_CAPM)
MAE_CAPM

0.020970330677320567

In [150]:
### FF3
reg_dict = {}
alpha_FF3 = []
model = LinearRegression()
X = df_factors[['MKT', 'SMB', 'HML']]
for col in df_test.columns:
    y = df_test[col]
    model.fit(X, y)
    alpha = model.intercept_.item() * AnnualizationFactor
    reg_dict[col] = (alpha, model.score(X,y))
    alpha_FF3.append(abs(alpha))
reg_dict

{'Agric': (0.01995200437321585, 0.3572836122155515),
 'Food ': (0.028691716101608693, 0.4041166791829469),
 'Soda ': (0.03189881722090511, 0.27344203306332515),
 'Beer ': (0.0457795421759657, 0.3518066920608397),
 'Smoke': (0.0692872855448976, 0.2311577790054432),
 'Toys ': (-0.03494930530612349, 0.5304880295156791),
 'Fun  ': (0.012064848248240487, 0.5952044273977266),
 'Books': (-0.03430801050299502, 0.6911098257421664),
 'Hshld': (0.01244466764563288, 0.5043381475569546),
 'Clths': (-0.010456757554471278, 0.573900970962221),
 'Hlth ': (-0.008172680681034342, 0.43507739571582515),
 'MedEq': (0.02636069006321523, 0.5955129058049629),
 'Drugs': (0.03986423731047998, 0.49954180649422986),
 'Chems': (-0.02920645793155561, 0.728360293593795),
 'Rubbr': (-0.001024772137122102, 0.6837101926164264),
 'Txtls': (-0.04767168126465273, 0.5862542859087594),
 'BldMt': (-0.016889968876074885, 0.7492266337531879),
 'Cnstr': (-0.021262072256441708, 0.6552422257912154),
 'Steel': (-0.06714147807858256

In [151]:
model.coef_

array([1.03480454, 0.00374271, 0.12467438])

In [152]:
MAE_FF3 = sum(alpha_FF3) / len(alpha_FF3)
MAE_FF3

0.024358059122629356

In [153]:
### FF5
reg_dict = {}
alpha_FF5 = []
model = LinearRegression()
X = df_factors[['MKT', 'SMB', 'HML', 'RMW', 'CMA']]
for col in df_test.columns:
    y = df_test[col]
    model.fit(X, y)
    alpha = model.intercept_.item() * AnnualizationFactor
    reg_dict[col] = (alpha, model.score(X,y))
    alpha_FF5.append(abs(alpha))
reg_dict

{'Agric': (0.0071693167416732075, 0.36189680032589133),
 'Food ': (-0.006417266962200737, 0.4781017031550969),
 'Soda ': (-0.00169553164325012, 0.30640278207789895),
 'Beer ': (0.00410416746808738, 0.4335645691889225),
 'Smoke': (0.020506595340591675, 0.2943616069680609),
 'Toys ': (-0.06288432301767417, 0.5509376996638676),
 'Fun  ': (0.024145721897980386, 0.5995113841202688),
 'Books': (-0.0488426929633155, 0.7021872588759339),
 'Hshld': (-0.02451722563738662, 0.5818837295084006),
 'Clths': (-0.04498676402573174, 0.629067740349132),
 'Hlth ': (-0.04897420039863376, 0.4905153784930124),
 'MedEq': (0.011556076496517728, 0.6045491991681019),
 'Drugs': (0.022556553362292394, 0.5189845285559775),
 'Chems': (-0.050796293966824994, 0.7461204328576003),
 'Rubbr': (-0.024183717995231006, 0.704417702705457),
 'Txtls': (-0.07698103091313799, 0.618309634596574),
 'BldMt': (-0.04356435658660536, 0.7800253686787557),
 'Cnstr': (-0.0440624767933959, 0.6727532140397003),
 'Steel': (-0.05847244390128

In [154]:
model.coef_

array([1.05357576, 0.05303602, 0.06876469, 0.16092121, 0.07900827])

In [155]:
MAE_FF5 = sum(alpha_FF5) / len(alpha_FF5)
MAE_FF5

0.03137208981381941

In [156]:
mae_table = pd.DataFrame({
    "Model": ["CAPM", "FF3", "FF5", "AQR"],
    "MAE": [MAE_CAPM, MAE_FF3, MAE_FF5, MAE_AQR]
})

mae_table.set_index("Model", inplace=True)
mae_table


MAE
Model          
CAPM   0.020970
FF3    0.024358
FF5    0.031372
AQR    0.024611

### Question 2(2) Answers

CAPM appears to have the smallest MAE out of the 4 models & has the best fit by that metric.

### Question 3: Factor Importance and Momentum Factor Analysis


#### Answer to Question 3

The market factor is immediately important. The robustness factor seems like the next most important factor. Momentum does not appear to be a significant factor because it's weighting is much less in the AQR model.